---
name: Renovate
on:
  push:
    branches:
      - main
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v42.0.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_ALLOWED_COMMANDS: "^./update_chart_ref.sh .*$"
          RENOVATE_REPOSITORIES: "['thejan2009/renovate-helmv3']"
